apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-svc-api
  name: connection-svc-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30015
  selector:
    service: connection-svc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-svc-api
  name: connection-svc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-svc-api
  template:
    metadata:
      labels:
        service: connection-svc-api
    spec:
      containers:
      - image: durbin164/udaconnect-connection-svc-api:latest
        name: connection-svc-api
        imagePullPolicy: Always
        env:
        - name: PERSON_SERVICE_ENDPOINT_GRPC
          valueFrom:
            configMapKeyRef:
              name: connection-svc-config
              key: PERSON_SERVICE_ENDPOINT_GRPC
        - name: LOCATION_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: connection-svc-config
              key: LOCATION_SERVICE_ENDPOINT
      restartPolicy: Always
