apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-frontend-app
  name: udaconnect-frontend-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30030
  selector:
    service: udaconnect-frontend-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-frontend-app
  name: udaconnect-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-frontend-app
  template:
    metadata:
      labels:
        service: udaconnect-frontend-app
    spec:
      containers:
      - image: durbin164/udaconnect-frontend-app:latest
        name: udaconnect-frontend-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "64m"
          limits:
            memory: "512Mi"
            cpu: "256m"
        env:
          - name: CI
            value: "true"
      restartPolicy: Always
