apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-visit-consumer
  name: person-visit-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-visit-consumer
  template:
    metadata:
      labels:
        service: person-visit-consumer
    spec:
      containers:
      - image: durbin164/udaconnect-person-visit-consumer:latest
        name: person-visit-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-location-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-location-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-location-map
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-location-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-location-map
              key: DB_PORT
      restartPolicy: Always
