apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-svc-grpc-api
  name: person-svc-grpc-api
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30017
  selector:
    service: person-svc-grpc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-svc-grpc-api
  name: person-svc-grpc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-svc-grpc-api
  template:
    metadata:
      labels:
        service: person-svc-grpc-api
    spec:
      containers:
      - image: durbin164/udaconnect-person-svc-grpc-api:latest
        name: person-svc-grpc-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-person-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-person-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-person-map
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-person-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-person-map
              key: DB_PORT
      restartPolicy: Always
