apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-visit-svc-api
  name: person-visit-svc-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30018
  selector:
    service: person-visit-svc-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-visit-svc-api
  name: person-visit-svc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-visit-svc-api
  template:
    metadata:
      labels:
        service: person-visit-svc-api
    spec:
      containers:
      - image: durbin164/udaconnect-person-visit-svc-api:latest
        name: person-visit-svc-api
        imagePullPolicy: Always
      restartPolicy: Always
